### ISSUE TITLE
Add log file and sam alignment file in SortMeRNA if required

### ISSUE THREAD

**Issue by smruthi98** [qiita-spots/qp-shotgun#64]
Current version only outputs ribosomal and non-ribosomal reads per sample (format: per_sample_fastq). Log or summary file can be added to indicate proportion of reads aligned to each database.

**Comment by antgonza** [comment]
@smruthi98, this issue was just mentioned again today and I think it will not be hard to implement but just to double check: do you know what's the flag/parameters to store the log file in SortMeRNA? Also, do you have an example of this log or what kind of information it contains? Thank you. 

cc: @justinshaffer, @RodolfoSalido.

**Comment by smruthi98** [comment]
The flag --log can be added to the SMR command to generate the log file. The log file gives the distribution of reads (%) mapping to each of the ribosomal databases screened.

**Comment by antgonza** [comment]
I'm starting to implement this and have a question. As a reminder we generate 2 outputs: 'Non-ribosomal reads' & 'Ribosomal reads', so which one should "hold" the log files?

**Comment by RodolfoSalido** [comment]
I think it would be appropriate for the 'Ribosomal reads’ artifact to hold the log file.

-Rodolfo
